In [1]:
import os
os.environ["HTTPS_PROXY"] = ""
os.environ["HTTP_PROXY"] = ""

In [2]:
import time
import pandas as pd
import numpy as np
import math

# internal tools
from dsgtools.reporting import make_format
from dsgtools.reporting import TableWriter
from dsgtools.reporting import freq
from dsgtools.reporting import bivariate

import warnings
warnings.filterwarnings('ignore')

In [5]:
from dsgtools import azure
ally = pd.read_adls("Analytics/RnD Projects/Product RnD/Credit/202311-CRD-Model-Revalidations/Auto_data/metro2_samples/CRD_Model_Revalidation_ALLY_Data.csv", 
                    verbose = False, low_memory = False, delimiter = "|")
print(ally.shape)

(1417490, 15)

In [9]:
freq(ally.orig_sample_wt)

                    Count  Pct  Cuml Count  Cuml Pct
orig_sample_wt
1.0             1417490.0  1.0   1417490.0       1.0

In [8]:
bivariate(ally.applicationdate.astype(str).str.slice(0, 6), ally.tag)

tag                    tag
stats                    N      PctN      Sum      Mean       WoE        IV
applicationdate
202101             75187.0  0.053042   2269.0  0.030178 -0.599728  0.014704
202102             69457.0  0.049000   2318.0  0.033373 -0.495792  0.009700
202103             97091.0  0.068495   4033.0  0.041538 -0.268444  0.004384
202104             88440.0  0.062392   3824.0  0.043238 -0.226558  0.002897
202105             90421.0  0.063790   4203.0  0.046483 -0.150812  0.001357
202106             82748.0  0.058376   4301.0  0.051977 -0.033307  0.000064
202107             84113.0  0.059339   4461.0  0.053036 -0.012026  0.000009
202108             78825.0  0.055609   4441.0  0.056340  0.051907  0.000153
202109             73514.0  0.051862   4259.0  0.057935  0.081508  0.000357
202110             76473.0  0.053950   4649.0  0.060793  0.132702  0.001008
202111             64933.0  0.045808   4065.0  0.062603  0.163975  0.001326
202112             63473.0  0.044778   3750.0  0.059080  0.102307  0.000491
202201             70195.0  0.049521   4024.0  0.057326  0.070303  0.000253
202202             75079.0  0.052966   4638.0  0.061775  0.149776  0.001271
202203             87109.0  0.061453   5732.0  0.065803  0.217240  0.003198
202204             81162.0  0.057258   5067.0  0.062431  0.161035  0.001596
202205             85158.0  0.060077   5253.0  0.061685  0.148229  0.001411
202206             74112.0  0.052284   4751.0  0.064106  0.189299  0.002040
Missing                0.0  0.000000      0.0  0.000000  0.000000  0.000000
Total            1417490.0  1.000000  76038.0  0.053643  0.000000  0.046218

In [10]:
bank = pd.read_adls("Analytics/RnD Projects/Product RnD/Credit/202311-CRD-Model-Revalidations/Bankcard_data/metro2_samples/CRD_Model_Revalidation_GLS_DISCOVER_Data.csv", 
                    verbose = False, low_memory = False, delimiter = "|")
print(bank.shape)

(1227877, 15)

In [13]:
bivariate(bank.client, bank.tag, sample_weight=bank.orig_sample_wt)

tag             tag
stats             N      PctN       Sum      Mean       WoE        IV
client
DISCOVER  4141126.0  0.946829  208871.0  0.050438  0.028956  0.000804
GLS        232555.0  0.053171    5742.0  0.024691 -0.712111  0.019782
Missing         0.0  0.000000       0.0  0.000000  0.000000  0.000000
Total     4373681.0  1.000000  214613.0  0.049069  0.000000  0.020586

In [15]:
freq(bank.client, bank.orig_sample_wt, cross = False, observed = True)

                            Count       Pct  Cuml Count  Cuml Pct
client   orig_sample_wt
GLS      1.0             232555.0  0.189396    232555.0  0.189396
DISCOVER 1.0             208871.0  0.170107    441426.0  0.359503
         5.0             786451.0  0.640497   1227877.0  1.000000

In [16]:
bivariate(bank.applicationdate.astype(str).str.slice(0, 6), bank.tag, sample_weight=bank.orig_sample_wt)

tag                    tag                                          \
stats                    N      PctN       Sum      Mean       WoE
applicationdate
202101            190599.0  0.043579    4770.0  0.025026 -0.698273
202102            172573.0  0.039457    5374.0  0.031140 -0.473405
202103            204802.0  0.046826    9609.0  0.046918 -0.047081
202104            194135.0  0.044387    8793.0  0.045293 -0.084039
202105            198519.0  0.045389    8774.0  0.044197 -0.109681
202106            206244.0  0.047156    8279.0  0.040142 -0.210160
202107            213337.0  0.048777    8106.0  0.037996 -0.267324
202108            212790.0  0.048652    8424.0  0.039588 -0.224620
202109            193718.0  0.044292    7522.0  0.038830 -0.244760
202110            190213.0  0.043490    7834.0  0.041185 -0.183406
202111            187931.0  0.042969    7925.0  0.042170 -0.158760
202112            186702.0  0.042688    7914.0  0.042388 -0.153360
202201            202335.0  0.046262    7643.0  0.037774 -0.273421
202202            192951.0  0.044116    9428.0  0.048862 -0.004448
202203            232768.0  0.053220   13472.0  0.057877  0.174399
202204            230420.0  0.052683   15070.0  0.065402  0.304649
202205            250884.0  0.057362   18168.0  0.072416  0.414051
202206            252683.0  0.057774   18246.0  0.072209  0.410967
202207            238856.0  0.054612   15196.0  0.063620  0.275113
202208            227736.0  0.052070   13274.0  0.058287  0.181882
202209            193485.0  0.044238   10792.0  0.055777  0.135206
Missing                0.0  0.000000       0.0  0.000000  0.000000
Total            4373681.0  1.000000  214613.0  0.049069  0.000000

tag
stats                      IV
applicationdate
202101           1.567932e-02
202102           7.177147e-03
202103           1.016192e-04
202104           3.018700e-04
202105           5.197980e-04
202106           1.896083e-03
202107           3.094328e-03
202108           2.220479e-03
202109           2.378977e-03
202110           1.347685e-03
202111           1.008686e-03
202112           9.373220e-04
202201           3.061928e-03
202202           8.712144e-07
202203           1.752030e-03
202204           5.617983e-03
202205           1.188352e-02
202206           1.177431e-02
202207           4.685142e-03
202208           1.870807e-03
202209           8.598165e-04
Missing          0.000000e+00
Total            7.816972e-02